Add env and update with new data releases
dhimmel/gene-ontology pull request #3
Opened 2018-10-26 22:20 UTC by markberger

I've added an `environment.yaml` file and generated the updated files by running `code/run.sh`.  I'm still fairly new to anaconda but I believe I've only included the necessary packages and their dependencies (networkx, pandas, obonet, and requests). Note that some of the files for taxa are now deleted because they are not in the latest version of the files.

2018-10-28 13:15 UTC, dhimmel requested changes
I think it'd be best to split the environment PR from the data update PR. Should we just revert the environment.yml change from this PR... then I think the data update is ready to merge.

Then in a subsequent PR we can do the the environment update. I don't want to take too much of your time, so let me know if you're reaching the max time you've got for this, or whether you're able to keep going with enhancing the environment spec.

2018-10-28 13:15 UTC, dhimmel commented on environment.yml
> +  - defaults
change the channel to conda-forge

2018-10-28 13:15 UTC, dhimmel commented on environment.yml
> +  - numpy=1.15.3=py36h1d66e8a_0
Remove build numbers for all packages, i.e. 

```
- conda-forge::numpy=1.15.3
```

I also usually specify the channel as done with `conda-forge::`.

The build numbers have the effect of making envs restricted to a single operating system (e.g. mac or linux).

It's also probably better to only specify the versions of packages that we explicitly import, such as `pandas` but not behind-the-scenes packages that apply specially to certain architectures such as `intel-openmp`.

See the example at https://github.com/greenelab/manubot-rootstock/blob/dcfe402544f90e0047a247cdd8d01a2bca08df54/build/environment.yml

2018-10-28 13:15 UTC, dhimmel commented on environment.yml
> +prefix: /opt/modules/pkgs/anaconda/3.6/envs/gene-ontology2
Remove prefix as this is device / user specific.

2018-10-28 13:16 UTC, dhimmel commented
> Note that some of the files for taxa are now deleted because they are not in the latest version of the files.

Great. glad that worked

2018-10-29 16:00 UTC, markberger commented
I've dropped `environment.yaml` from this commit so that it is just the data update. I can make the changes to the spec and test them out but it probably won't be for a few days.

2018-10-29 18:10 UTC, dhimmel approved these changes
Great. Thanks for the update. Always exciting to see a community contribution like this to help keep things up to date (although ideally we'd automate the updates with continuous analysis).

2018-10-29 18:12 UTC, merged

2018-10-29 18:37 UTC, dhimmel commented
> . I can make the changes to the spec and test them out but it probably won't be for a few days

Not a problem. Feel free to open a WIP progress with the old env if you'd like, such that if you don't have time we can always use that as a starting point!